"""Bring this box's containers to one version — the deploy webhook's and the
installer's last step.

    python3 cloud_deploy.py v2026.10.3     # a release: pull that image
    python3 cloud_deploy.py master         # the development image
    python3 cloud_deploy.py --build NAME   # no image to pull: build here, tag NAME

In order: size the worker set (`cloud_workers.py`), record the version in `.env`
(`SPLOUCH_VERSION`, which compose and every worker read), pull the image — or build
it here when asked to, or when the registry has none (a fork, or CI not done yet
for a tag just pushed: the build then stands in), or when the one pulled was built
from another commit than this checkout (`master` updated before CI published it) —
start the containers, start or
stop the monitoring stack (`MONITORING=1` in `.env`, `cloud/monitoring/`), and
reload Caddy for the routes, which keeps every open socket.

The image is `SPLOUCH_IMAGE` from `.env`, default the project's
(`ghcr.io/olivierouellet/splouch-cloud`). Runs on the host, standard library only.
"""

import os
import subprocess
import sys

import cloud_workers

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
DEFAULT_IMAGE = "ghcr.io/olivierouellet/splouch-cloud"
# The commit an image was built from: CI and the local build both stamp it
# (cloud/Dockerfile, `SPLOUCH_COMMIT`).
REVISION_LABEL = "org.opencontainers.image.revision"
BUILD_OVERRIDE = "docker-compose.build.yml"
MONITORING_COMPOSE = os.path.join("monitoring", "docker-compose.yml")
AGENT_COMPOSE = os.path.join("monitoring", "agent.yml")
AGENT_CONFIG = os.path.join(HERE, "monitoring", "agent", "prometheus.yml")
ROLES_ROUTE = os.path.join(HERE, "caddy.d", "roles.caddy")
GRAFANA_ROUTE = os.path.join(HERE, "caddy.d", "monitoring.caddy")
STATUS_SITE = os.path.join(HERE, "caddy.d", "monitoring.site")


def set_env(key, value, path=None):
    """Write `key=value` into `.env`, replacing any earlier line for it."""
    path = path or cloud_workers.ENV_FILE
    try:
        with open(path, encoding="utf-8") as f:
            lines = f.read().splitlines()
    except OSError:
        lines = []
    lines = [ln for ln in lines if not ln.startswith(f"{key}=")] + [f"{key}={value}"]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def profiles(env):
    """COMPOSE_PROFILES for this server's parts: `control`, `workers`, both."""
    return ",".join(sorted(cloud_workers.roles(env) & {"control", "workers"}))


def _compose(*args, build=False, env=None, commit=""):
    """A `docker compose` command over this node's files and parts, plus the build
    override when asked, stamping what it builds with `commit`."""
    files = cloud_workers.COMPOSE_FILES + (f":{BUILD_OVERRIDE}" if build else "")
    extra = {"COMPOSE_FILE": files}
    if env is not None:
        extra["COMPOSE_PROFILES"] = profiles(env)
    if commit:
        extra["SPLOUCH_COMMIT"] = commit
    return ["docker", "compose", *args], {**os.environ, **extra}


def _output(runner, argv):
    """A command's stripped stdout, or '' when it fails or prints nothing."""
    r = runner(
        argv,
        env=dict(os.environ),
        cwd=HERE,
        check=False,
        capture_output=True,
        text=True,
    )
    return (getattr(r, "stdout", "") or "").strip() if r.returncode == 0 else ""


def stale_image(env, version, runner):
    """Whether the image just pulled was built from another commit than this
    checkout. `master` is the case: the webhook checks the new commit out at once,
    while CI takes minutes to publish its image, so the pull gets the last one.

    Not stale when this checkout's commit cannot be read, or for a release whose
    image carries no stamp (published before images were stamped): its tag only
    ever names the one build. A `master` image with no stamp is stale — it is older
    than this check.
    """
    head = _output(runner, ["git", "-C", REPO, "rev-parse", "HEAD"])
    if not head:
        return False
    image = f"{env.get('SPLOUCH_IMAGE') or DEFAULT_IMAGE}:{version}"
    built = _output(
        runner,
        [
            "docker",
            "image",
            "inspect",
            "--format",
            f'{{{{ index .Config.Labels "{REVISION_LABEL}" }}}}',
            image,
        ],
    )
    if built in ("", "<no value>"):
        return version == "master"
    return built != head


HEADER = "# Generated by cloud_deploy.py on every deploy — do not edit, not tracked.\n"


def roles_routes(env):
    """The catch-all and the workers' API for this server's parts.

    With the control plane here, it takes everything no other route claims —
    `/.well-known/` included, which the QR hand-off needs unredirected (docs/app.md
    `P-16`). `/internal/*` is refused publicly unless `REMOTE_NODES=1`, when workers
    on other servers reach it over HTTPS with `NODE_SECRET`. A workers-only node
    sends everything else to the meet list on the control plane.
    """
    if "control" in cloud_workers.roles(env):
        internal = (
            "    reverse_proxy control:8000"
            if env.get("REMOTE_NODES") == "1"
            else "    respond 404"
        )
        rest = "    reverse_proxy control:8000"
    else:
        internal = "    respond 404"
        picker = (env.get("PICKER_URL") or env.get("CONTROL_URL") or "").rstrip("/")
        rest = f"    redir {picker}{{uri}} 302" if picker else "    respond 404"
    return (
        HEADER + f"handle /internal/* {{\n{internal}\n}}\n" + f"handle {{\n{rest}\n}}\n"
    )


def agent_config(env):
    """A remote node's Prometheus agent: scrape what is here, send it to the
    monitoring server over WireGuard (docs/architecture/scaling.md). Nothing on a
    node listens for it."""
    r = cloud_workers.roles(env)
    jobs = []
    if "control" in r:
        jobs.append(
            "  - job_name: control\n    static_configs:\n"
            '      - targets: ["control:8000"]\n        labels: {role: control}\n'
        )
    if "workers" in r:
        jobs.append(
            "  - job_name: workers\n    file_sd_configs:\n"
            '      - files: ["/etc/prometheus/targets/workers.json"]\n'
        )
    jobs.append(
        '  - job_name: node\n    static_configs:\n      - targets: ["node-exporter:9100"]\n'
    )
    jobs.append(
        '  - job_name: containers\n    static_configs:\n      - targets: ["cadvisor:8080"]\n'
    )
    name = env.get("NODE_NAME", "") or "node"
    hub = env.get("WG_HUB", "").strip()
    return (
        "# Generated by cloud_deploy.py on every deploy — do not edit, not tracked.\n"
        "global:\n  scrape_interval: 15s\n"
        f"  external_labels: {{node: {name}}}\n"
        f"remote_write:\n  - url: http://{hub}:9090/api/v1/write\n"
        "scrape_configs:\n" + "".join(jobs)
    )


def _write_or_remove(path, text):
    if text:
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
    elif os.path.exists(path):
        os.remove(path)


def monitoring_routes(env):
    """Caddy's routes to the monitoring stack, or none when it is off: Grafana at
    `/grafana/` on this site, and Uptime Kuma's status page on `STATUS_DOMAIN` once
    the admin gives it one (its first visitor creates the admin account, so not
    before it is set up — docs/cloud.md)."""
    on = "monitoring" in cloud_workers.roles(env)
    grafana = (
        "# Generated by cloud_deploy.py when MONITORING=1 — do not edit, not tracked.\n"
        "handle /grafana* {\n    reverse_proxy grafana:3000\n}\n"
        if on
        else ""
    )
    domain = env.get("STATUS_DOMAIN", "").strip()
    status = (
        "# Generated by cloud_deploy.py when MONITORING=1 — do not edit, not tracked.\n"
        f"{domain} {{\n    reverse_proxy uptime-kuma:3001\n}}\n"
        if on and domain
        else ""
    )
    return grafana, status


def deploy(version, build=False, runner=subprocess.run):
    """Bring this box to `version`. Returns 0, or the exit code of the step that
    failed — before `up`, the running containers are left as they were."""

    def sh(argv_env):
        argv, env = argv_env
        return runner(argv, env=env, cwd=HERE, check=False).returncode

    def has_containers(cmd):
        """Whether a compose project has containers to stop. A failed check says
        yes, so `down` still runs and reports what is wrong."""
        r = runner(
            [*cmd, "ps", "-a", "-q"],
            env=dict(os.environ),
            cwd=HERE,
            check=False,
            capture_output=True,
            text=True,
        )
        return r.returncode != 0 or bool((r.stdout or "").strip())

    count = cloud_workers.worker_count(cloud_workers.read_env())
    cloud_workers.write(count)
    set_env("SPLOUCH_VERSION", version)
    print(f"{count} relay worker(s), version {version}", flush=True)

    env = cloud_workers.read_env()
    parts = cloud_workers.roles(env)
    ours = [
        svc
        for svc, part in (("control", "control"), ("app", "workers"))
        if part in parts
    ]
    _write_or_remove(ROLES_ROUTE, roles_routes(env))

    if ours and not build and sh(_compose("pull", "--quiet", *ours, env=env)):
        print("no image to pull for this version — building it here", flush=True)
        build = True
    elif ours and not build and stale_image(env, version, runner):
        # Built here under the same tag, so compose runs it; the next deploy's pull
        # replaces it with CI's once that is published.
        print("the image pulled is not this commit's — building it here", flush=True)
        build = True
    if ours and build:
        head = _output(runner, ["git", "-C", REPO, "rev-parse", "HEAD"])
        code = sh(_compose("build", ours[0], build=True, env=env, commit=head)) or sh(
            _compose(
                "up", "-d", "--pull", "never", "--remove-orphans", build=True, env=env
            )
        )
    else:
        code = sh(_compose("up", "-d", "--remove-orphans", env=env))
    if code:
        return code

    # The monitoring stack (the `monitoring` part), or — on a server without it
    # that has a WireGuard hub to send to — the node agent. Each is its own compose
    # project on this one's network.
    grafana, status = monitoring_routes(env)
    _write_or_remove(GRAFANA_ROUTE, grafana)
    _write_or_remove(STATUS_SITE, status)
    for compose, on in (
        (MONITORING_COMPOSE, "monitoring" in parts),
        (
            AGENT_COMPOSE,
            "monitoring" not in parts and bool(env.get("WG_HUB", "").strip()),
        ),
    ):
        if compose == AGENT_COMPOSE and on:
            os.makedirs(os.path.dirname(AGENT_CONFIG), exist_ok=True)
            _write_or_remove(AGENT_CONFIG, agent_config(env))
        cmd = ["docker", "compose", "--env-file", ".env", "-f", compose]
        if not on and not has_containers(cmd):
            continue  # never started here: nothing to stop, and no warning about it
        cmd += ["up", "-d", "--remove-orphans"] if on else ["down", "--remove-orphans"]
        code = sh((cmd, dict(os.environ)))
        if code:
            return code
    return sh(
        _compose(
            "exec",
            "-T",
            "caddy",
            "caddy",
            "reload",
            "--config",
            "/etc/caddy/Caddyfile",
            "--adapter",
            "caddyfile",
        )
    )


if __name__ == "__main__":
    args = sys.argv[1:]
    build = "--build" in args
    names = [a for a in args if a != "--build"]
    if len(names) != 1:
        sys.exit("usage: cloud_deploy.py [--build] VERSION")
    sys.exit(deploy(names[0], build))
