"""Write this node's worker set: one relay process per spare core.

A relay worker is one Python process, so it uses at most one core
(docs/architecture/scaling.md). This sizes the set from the machine and writes the
two files that run it, both untracked and regenerated on every deploy:

* ``docker-compose.workers.yml`` — ``app2`` … ``appN``, each the ``app`` service
  from ``docker-compose.yml`` with its own ``WORKER`` number. ``app`` is worker 1.
* ``caddy.d/workers.caddy`` — one ``/wN/*`` route per worker, imported by the
  Caddyfile. Caddy strips the prefix, so a worker serves the same paths as ever.

It also makes sure ``.env`` names both compose files in ``COMPOSE_FILE``, so every
``docker compose`` command run in this directory sees the whole set.

    python3 cloud_workers.py            # N = WORKERS from .env, else cores − reserved
    python3 cloud_workers.py 4          # exactly 4

Runs on the host (the deploy webhook and the installer call it), so it uses the
standard library only. Reserved cores: ``RESERVED_CORES`` in ``.env``, default 2 —
Caddy, the control plane and Postgres share them on a box that runs everything.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ENV_FILE = os.path.join(HERE, ".env")
COMPOSE_OUT = os.path.join(HERE, "docker-compose.workers.yml")
CADDY_OUT = os.path.join(HERE, "caddy.d", "workers.caddy")
COMPOSE_FILES = "docker-compose.yml:docker-compose.workers.yml"


def read_env(path=ENV_FILE):
    env = {}
    try:
        with open(path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, _, v = line.partition("=")
                    env[k.strip()] = v.strip()
    except OSError:
        pass
    return env


def worker_count(env, cores=None):
    """WORKERS when set, else every core but the reserved ones; never below 1."""
    try:
        if int(env.get("WORKERS", "") or 0) > 0:
            return int(env["WORKERS"])
    except ValueError:
        pass
    cores = cores or os.cpu_count() or 1
    try:
        reserved = int(env.get("RESERVED_CORES", "") or 2)
    except ValueError:
        reserved = 2
    return max(1, cores - reserved)


def compose_override(n):
    """`app2`…`appN`, each extending `app` with its own number. Every worker,
    `app` included, learns how many there are, which its node reports."""
    lines = [
        "# Generated by cloud_workers.py on every deploy — do not edit, not tracked.",
        "services:",
        "  app:",
        "    environment:",
        f'      NODE_WORKERS: "{n}"',
    ]
    for i in range(2, n + 1):
        lines += [
            f"  app{i}:",
            "    extends:",
            "      file: docker-compose.yml",
            "      service: app",
            "    environment:",
            f'      WORKER: "{i}"',
            f'      NODE_WORKERS: "{n}"',
        ]
    return "\n".join(lines) + "\n"


def caddy_routes(n):
    lines = [
        "# Generated by cloud_workers.py on every deploy — do not edit, not tracked."
    ]
    for i in range(1, n + 1):
        upstream = "app" if i == 1 else f"app{i}"
        lines += [f"handle_path /w{i}/* {{", f"    reverse_proxy {upstream}:5000", "}"]
    return "\n".join(lines) + "\n"


def ensure_compose_file(path=ENV_FILE):
    """Name both compose files in `.env`, so `docker compose` anywhere here uses them."""
    try:
        with open(path, encoding="utf-8") as f:
            lines = f.read().splitlines()
    except OSError:
        return
    want = f"COMPOSE_FILE={COMPOSE_FILES}"
    if want in lines:
        return
    lines = [ln for ln in lines if not ln.startswith("COMPOSE_FILE=")] + [want]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def write(n):
    os.makedirs(os.path.dirname(CADDY_OUT), exist_ok=True)
    with open(COMPOSE_OUT, "w", encoding="utf-8") as f:
        f.write(compose_override(n))
    with open(CADDY_OUT, "w", encoding="utf-8") as f:
        f.write(caddy_routes(n))
    ensure_compose_file()


if __name__ == "__main__":
    count = int(sys.argv[1]) if len(sys.argv) > 1 else worker_count(read_env())
    write(max(1, count))
    print(f"{count} relay worker(s)")
